### ISSUE TITLE
The extension is keep loading the local csproj and never show any project references.

### ISSUE THREAD

**Issue by Mutuduxf** [aliasadidev/vscode-npm-gui#61]
The vscode (1.75.1) and extension is upgraded to the latest version and looks like this:

![image](https://user-images.githubusercontent.com/32291429/222082113-07889afe-0115-4b5f-906e-0e6cc5beb42f.png)

and I don't know if that is the reason.

![image](https://user-images.githubusercontent.com/32291429/222082296-4b6a391e-91ad-409d-a924-77d4b6aca278.png)

**Comment by Dragod** [comment]
I don't get that error but the plugin do not found any pnuget package from csproj file while I have plenty

**Comment by Mutuduxf** [comment]
> I don't get that error but the plugin do not found any nuget package from csproj file while I have plenty https://x.pfcode.net/VujE3/nIvoqiHo15.png

This error was occurred on my laptop, the same solution works fine on a desktop.

**Comment by aliasadidev** [comment]
@Dragod @Mutuduxf 

Could you please provide the following information:

- Version of VSCode
- The .csproj file causing the problem
- Operating System
- Version of vscode-npm-gui

**Comment by stephannn** [comment]
Hi,
I will just hijack this issue description because I feel like I have the same problem with on of my projects:
System: Ubuntu 24.04
VSC: 1.91.1
NPM-GUI: 2.1.0

My Project file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.1" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.1" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.1" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.1" />
    <!-- <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" /> -->
  </ItemGroup>
</Project>
``` 
So when ever I start the extension it just keeps on the loading screen. Other projects like Asp.net Core work like charm. I also cannot find any logs. 

Edit:
Or can anyone tell me how to debug it? I cannot see any log for that extension.

Edit2:
When I click in VSC on _Help - Toggle Debugger Tools_ I can see following error:
```
polyfills.5fb6c6c595e697c7.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at Object.next (main.fcd6bba925869588.js:1:24515)
    at Ge.next (vendor.ddc0912aba27c337.js:1:5217)
    at Be._next (vendor.ddc0912aba27c337.js:1:4892)
    at Be.next (vendor.ddc0912aba27c337.js:1:4580)
    at Object.callback (main.fcd6bba925869588.js:1:2038)
    at scripts.81265022c8276427.js:1:509
    at v.invokeTask (polyfills.5fb6c6c595e697c7.js:1:7219)
    at L.runTask (polyfills.5fb6c6c595e697c7.js:1:2599)
    at p.invokeTask [as invoke] (polyfills.5fb6c6c595e697c7.js:1:8270)
    at Z (polyfills.5fb6c6c595e697c7.js:1:20806)
```

When I click on the error I get following JS code :
```
t.type == P && t.data && !t.data.isPeriodic && (t.cancelFn = void 0);
                            try {
                                return this._zoneDelegate.invokeTask(this, t, r, k)
                            } catch (l) {
                                if (this._zoneDelegate.handleError(this, l))
                                    throw l
                            }
```

Edit 3:
I just disabled the extension _Avalonia for VSCode_ and now it is working. No idea what is the connection between there.
